version: 2

models:
  - name: raw_movie_titles
    columns:
      - name: release_year
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1925
              max_value: 2022
      - name: type
        tests:
          - accepted_values:
              values: ['Movie']
      - name: show_id
        tests:
          - is_id_valid

